language: python
python:
    - "3.6"
    - "3.7-dev"
install:
    - pip install .
    - pip install codecov
    - pip install coverage
script:
    - pytest
    - coverage run tests/run_all_test.py
after_success:
    - codecov